# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170110_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
