# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_webpage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.TextField(),
        ),
    ]
