# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170110_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
